package com.schoolmanagementsystem.schoolManagementSystem.business.abstracts;

import java.util.List;

import com.schoolmanagementsystem.schoolManagementSystem.business.requests.departmentTypeRequests.CreateDepartmentTypeRequest;
import com.schoolmanagementsystem.schoolManagementSystem.business.requests.departmentTypeRequests.DeleteDepartmentTypeRequest;
import com.schoolmanagementsystem.schoolManagementSystem.business.requests.departmentTypeRequests.UpdateDepartmentTypeRequest;
import com.schoolmanagementsystem.schoolManagementSystem.business.responses.departmentTypeResponses.GetAllDepartmentTypeResponse;
import com.schoolmanagementsystem.schoolManagementSystem.business.responses.departmentTypeResponses.GetByIdDepartmentTypeResponse;
import com.schoolmanagementsystem.schoolManagementSystem.core.utilities.results.DataResult;
import com.schoolmanagementsystem.schoolManagementSystem.core.utilities.results.Result;

public interface DepartmentTypeService {
	Result add(CreateDepartmentTypeRequest createDepartmentTypeRequest);

	Result delete(DeleteDepartmentTypeRequest deleteDepartmentTypeRequest);

	Result update(UpdateDepartmentTypeRequest updateDepartmentTypeRequest);

	DataResult<List<GetAllDepartmentTypeResponse>> getAll();

	DataResult<GetByIdDepartmentTypeResponse> getById(int id);
}
