package com.schoolmanagementsystem.schoolManagementSystem.business.abstracts;

import java.util.List;

import com.schoolmanagementsystem.schoolManagementSystem.business.requests.departmentTypeRequests.CreateDepartmentTypeRequest;
import com.schoolmanagementsystem.schoolManagementSystem.business.requests.departmentTypeRequests.DeleteDepartmentTypeRequest;
import com.schoolmanagementsystem.schoolManagementSystem.business.requests.departmentTypeRequests.UpdateDepartmentTypeRequest;
import com.schoolmanagementsystem.schoolManagementSystem.business.responses.departmentTypeResponses.GetAllDepartmentTypeResponse;
import com.schoolmanagementsystem.schoolManagementSystem.business.responses.departmentTypeResponses.GetByIdDepartmentTypeResponse;

public interface DepartmentTypeService {
	void add(CreateDepartmentTypeRequest createDepartmentTypeRequest);

	void delete(DeleteDepartmentTypeRequest deleteDepartmentTypeRequest);

	void update(UpdateDepartmentTypeRequest updateDepartmentTypeRequest);

	List<GetAllDepartmentTypeResponse> getAll();

	GetByIdDepartmentTypeResponse getById(int id);
}
